Homework 3
StanchykAF/NastassiaStanchyk-mobile pull request #2
Opened 2023-08-31 07:31 UTC by StanchykAF

2023-09-05 17:40 UTC, MaksimMeshcheriakovEPAM requested changes
Не вполне понятно, зачем вы практически дублируете код проекта для второй и третьей работы, причем храните его в одном проекте.  На мой взгляд достаточно было сделать небольшие дополнения в конфигурационных файлах и может быть кое-где в коде. 
Кроме того, есть замечания в комментариях в коде ПР.

2023-09-05 17:40 UTC, MaksimMeshcheriakovEPAM commented on src/main/java/hw3/setup/BaseTest.java
> +            URL url = new URL("https://ondemand.eu-central-1.saucelabs.com:443/wd/hub");
У вас же зачитывался URL через ts.appium во 2й работе? Зачем же вы его захардкодили здесь?

2023-09-05 17:40 UTC, MaksimMeshcheriakovEPAM commented on src/main/java/hw3/setup/BaseTest.java
> +        sauceOptions.setCapability("username", System.getProperty("username"));
насколько я понимаю, вы зачитываете значения username и accessKey из переменных среды, которые должны быть установлены в среде выполнения теста (на компе)? В таком случае сразу 2 ошибки:
- для переменных среды принята другая нотация (большие буквы и snake style)
- должна быть инструкция по запуску (README.md), где это должно быть написано (среди прочего). В противном случае пользователь должен сперва изучить ваш код. Обычно так не делают.

2023-09-05 17:40 UTC, MaksimMeshcheriakovEPAM commented on src/main/java/hw3/flow/GooglePageFlow.java
> +        return getPo().getWelement("searchResults").getText().contains(query);
Я не обратил внимания при проверке второй ДЗ, но такая проверка не до конца валидна. Вы проверяете только наличие шаблона в заголовке списка ссылок на ресурсы, которые представляются как результаты поиска. Но сами ресурсы по ссылкам вы не проверяете. А если там будут ссылки, не имеющие отношения к шаблону? Более правильным было бы проверять на соответствие шаблону все элементы выдачи. Для этого поле searchResults должно быть списком WebElements, и локатор надо чуть модернизировать, чтобы он указывал на элементы списка, а не на корневой элемент.

2023-09-05 17:40 UTC, MaksimMeshcheriakovEPAM commented on src/test/resources/remoteWebTNG.xml
> +    <parameter name="platformVersion" value="current_major"/>
вот так лучше не делать. Вы не можете предсказать, какое именно значение параметра будет при каждом конкретном запуске. Между тем нередко бывает что очередное обновление версии платформы включает существенные изменения, которые могут повлиять на рез-ты прохождения тестов. Параметры среды выполнения нужно четко фиксировать, чтобы иметь возможность выяснить, при каких значения тесты проходят, а при каких - нет.

2023-09-05 17:40 UTC, MaksimMeshcheriakovEPAM commented on src/test/resources/remoteiOSWebTNG.xml
> +    <parameter name="platformVersion" value="current_major"/>
нефиксированный параметр среды - по сути ошибка.

2023-09-18 15:11 UTC, StanchykAF commented on src/test/resources/remoteiOSWebTNG.xml
> +    <parameter name="platformVersion" value="current_major"/>
Произошло недопонимание с моей стороны. Версия зафиксирована.

2023-09-18 15:11 UTC, StanchykAF commented on src/test/resources/remoteWebTNG.xml
> +    <parameter name="platformVersion" value="current_major"/>
Произошло недопонимание с моей стороны. Версия зафиксирована.

2023-09-18 15:12 UTC, StanchykAF commented on src/main/java/hw3/setup/BaseTest.java
> +        sauceOptions.setCapability("username", System.getProperty("username"));
Нотация исправлена. Инструкция присутствует (также внесены соответствующие правки)

2023-09-18 15:15 UTC, StanchykAF commented on src/main/java/hw3/setup/BaseTest.java
> +            URL url = new URL("https://ondemand.eu-central-1.saucelabs.com:443/wd/hub");
При подстановке через ts.appium как во 2й работе 
appiumDriver = new AppiumDriver(new URL(System.getProperty("ts.appium")), capabilities);
были проблемы, поэтому был оставлен хардкод url. 
Исправлено.

2023-09-19 20:34 UTC, MaksimMeshcheriakovEPAM reviewed
Исправления версий и Appium URL приняты. 
Однако все так же осталась без изменений и пояснений проверка шаблона только для одного рез-та выдачи - а их вообще-то несколько (много). И как насчет валидности всех остальных?
Кроме того, судя по коду веб-теста - он не будет работать для ios safari. Это скорее всего проблема драйвера, но я давал рекомендации как это обойти (способы нивелирования ошибок в сторонних библиотеках также часть работы автоматизатора)

2023-09-19 20:34 UTC, MaksimMeshcheriakovEPAM commented on src/test/resources/remoteAndroidNativeTNG.xml
> +    <parameter name="app" value="EPAMTestApp.apk"/>
deviceOrientation и patformVersion на мой взгляд избыточны (вы ужесточаете условия подбора целевых устройств и тем самым повышаете хрупкость тестов, а сценарии тестов в этой информации вообще-то не нуждаются), но если работает - то ок, оставим как есть. 
То же замечание и для остальных конфигурационных xml файлов.

2023-09-19 21:00 UTC, StanchykAF commented on src/main/java/hw3/flow/GooglePageFlow.java
> +        return getPo().getWelement("searchResults").getText().contains(query);
исправлено. Однако результаты, не имеющие отношения к теме поиска, могут присутствовать в выдаче. Например, реклама.

2023-09-21 18:42 UTC, StanchykAF commented on src/test/resources/remoteAndroidNativeTNG.xml
> +    <parameter name="app" value="EPAMTestApp.apk"/>
deviceOrientation убрала. Без patformVersion не запускается тест
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Unable to parse remote response: Internal processing error, please contact SauceLabs support.

2023-09-25 19:31 UTC, MaksimMeshcheriakovEPAM approved these changes

2023-09-25 19:31 UTC, MaksimMeshcheriakovEPAM commented on src/main/java/hw3/utils/TestContext.java
Вы создали этот класс фактически чтобы 5 раз проверить platformName и в соответствии с его значением скорректировать поведение теста. Вообще-то вы в любой момент можете получить значение этого параметра прямо из драйвера, который создаете при старте теста, т. к. он содержит Desired Capabilities: 
getDriver().getPlatformName() (ну или то же самое но немного длинее вызов через getCapabilities()). 
А вот геттер вы сделали любопытный 😊.

2023-09-25 19:40 UTC, merged